### PR TITLE
11.4.0

### PR DESCRIPTION
**Pull request by typeling1578**

### CODE REVIEW

**Review by dominichayesferen — APPROVED** [review]
LGTM, can't find anything broken in this release.

Although, we'll probably want a newline on the Flatpak contributors in the about dialog, as it's starting to teeter towards getting cut off.

**Comment by typeling1578** [comment]
buildbot is down. :(

**Comment by dominichayesferen** [comment]
Oh, NOW you wake up... just to get interrupted, oof.

**Comment by typeling1578** [comment]
@flathubbot bot, build

**Pull request merged**
