### PR TITLE
11.10.0

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
Not sure what I did wrong here...

**Comment by TheChilledBuffalo** [comment]
bot, build

**Comment by bbhtt** [comment]
You have to add a launchable entry in the metainfo file see https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#launchable

**Comment by dominichayesferen** [comment]
bot, build

**Comment by dominichayesferen** [comment]
...
ugh, fine, guess we gotta rebuild again for GitHub to realise.

**Comment by dominichayesferen** [comment]
bot, build

**Comment by dominichayesferen** [comment]
Nevermind, I guess not.

**Comment by dominichayesferen** [comment]
@bbhtt I guess feel free to force-merge this when you're back online if BuildBot doesn't actually respond by then.

At its current commits, this MR is GTM.

**Review by dominichayesferen — APPROVED** [review]

**Comment by dominichayesferen** [comment]
thank

**Pull request merged**
