### PR TITLE
Set `security.sandbox.warn_unprivileged_namespaces` to `false`

### PR DESCRIPTION
**Pull request by typeling1578**
Temporary fix for bug 1909832

### CODE REVIEW

**Comment by dominichayesferen** [comment]
@flathubbot buildbot, build

**Comment by typeling1578** [comment]
Perhaps the queue is full.
image

**Comment by dominichayesferen** [comment]
I would guess, but surely the build request queue would at least be infinite on Buildbot?

**Comment by dominichayesferen** [comment]
my bad if it isn't, but the fact the build request queue is showing submissions from _"seconds ago"_...

**Pull request merged**
