### PR TITLE
Added actual captions for the screenshots

### LINKED ISSUE #49: Write better captions
All captions right now are `screenshot` either write correct ones or don't have this tag

https://github.com/flathub/one.ablaze.floorp/blob/master/one.ablaze.floorp.appdata.xml#L26

### PR DESCRIPTION
**Pull request by dominichayesferen**
fix #49

### CODE REVIEW

**Comment by dominichayesferen** [comment]
@razzeee Wrote these up real quick while waiting for build bot on the other pull request - are these valid enough captions?

**Comment by razzeee** [comment]
Seems way better

**Comment by dominichayesferen** [comment]
Alright, I'll hold off from getting this merged until #50 is, so it can be rebased on it.

**Comment by dominichayesferen** [comment]
~~not that it matters since I bet BuildBot would forget to tell GitHub this MR is ready to merge, too, anyway if I didn't cancel the job~~

**Comment by dominichayesferen** [comment]
bot, build

**Pull request merged**
