### PR TITLE
Add filesystem permissions for SSB support

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
Here's the draft PR for the feature in the Floorp-core repo: https://github.com/Floorp-Projects/Floorp-core/pull/63

### CODE REVIEW

**Comment by TheChilledBuffalo** [comment]
@dominichayesferen doesn't `:create` give that permission?

image

https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html

**Comment by TheChilledBuffalo** [comment]
I'll also add `:create` to the icons folder.

**Review by typeling1578 — APPROVED** [review]

**Comment by TheChilledBuffalo** [comment]
@typeling1578 Hey, may I ask why this was marked as a draft?

**Comment by dominichayesferen** [comment]
> @typeling1578 Hey, may I ask why this was marked as a draft?

To prevent accidental early merging until the upstream PR is added in, pretty sure.

**Comment by TheChilledBuffalo** [comment]
Upstream PR has been merged!

**Comment by dominichayesferen** [comment]
bot, build

**Pull request merged**
