### PR TITLE
11.5.0-lightning

### PR DESCRIPTION
**Pull request by typeling1578**

### CODE REVIEW

**Comment by dominichayesferen** [comment]
Wouldn't it make more sense for Lightning to be its own Flatpak ID, e.g.: one.ablaze.floorp-lightning?

**Comment by typeling1578** [comment]
No, the non-lightning version will remain.
Only the `lightning` branch will be added.

The normal version can still be installed.
```
flatpak install flathub one.ablaze.floorp
```

To install the lightning version:
```
flatpak install flathub one.ablaze.floorp//lightning
```

**Comment by typeling1578** [comment]
Ok, I will consider it, but since it is a sub-brand, I am not sure if it is worth getting a new ID.

Side-note: At this time, there are no plans to distribute a beta version.

**Comment by typeling1578** [comment]
bot, build

**Pull request merged**
